# Generated by Django 3.1.5 on 2021-03-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_requestbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requestbook',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'In Progress'), (20, 'Confirmed'), (30, 'Reject'), (40, 'Sent via mail Service'), (50, 'received Book'), (60, 'Sent Back'), (70, 'Received Back (Final)')]),
        ),
    ]
