# Generated by Django 3.1.5 on 2021-03-21 10:26

from django.db import migrations



def forwards(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all().iterator():
        user.email = user.username + user.email
        user.save(update_fields=('email', ))  # TODO use F function


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contactus'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]